apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-spec
  namespace: default
data:
  capability.yaml: |
    naftiko: "1.0.0-alpha3"
    info:
      label: Hello World
      labels:
        naftiko.io/tier: standard
    capability:
      exposes:
        - type: rest
          address: "0.0.0.0"
          port: 3001
          namespace: tutorial
          resources:
            - path: /hello
              name: hello
              operations:
                - method: GET
                  outputParameters:
                    - name: message
                      type: string
                      value: "Hello, World!"
        - type: control
          address: "0.0.0.0"
          port: 9090
          observability:
            enabled: true
            metrics:
              local:
                enabled: true
